version: "3"
services:
  sonarqube:
    image: sonarqube:latest
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - db
    environment:
      TZ: "Asia/Bangkok"
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_CE_JAVAOPTS: "-Xmx8G -Xms8G"
      SONAR_SEARCH_JAVAOPTS: "-Xmx8G -Xms8G"
      SONAR_WEB_JAVAOPTS: "-Xmx8G -Xms8G"
      SONAR_WEB_JAVAADDITIONALOPTS: "-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.18.0.jar=web"
      SONAR_CE_JAVAADDITIONALOPTS: "-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.18.0.jar=web"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    restart: always
  db:
    image: postgres:latest
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    restart: always

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
